version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_HOST:  database
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD:  super-cool-password

  redis:
    image:  redis
  
  database:
    image:  postgres
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD:  super-cool-password
    volumes:
      -  db-data:/var/lib/postgresql/data

volumes:
  db-data: